"""Initial migration with Keycloak support

Revision ID: 6b1a23229230
Revises: 
Create Date: 2025-06-09 12:55:17.038620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1a23229230'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellido', sa.String(length=64), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('keycloak_id', sa.String(length=100), nullable=True),
    sa.Column('is_keycloak_user', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('legajo_evaluador', sa.String(length=20), nullable=True),
    sa.Column('departamento_academico', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('keycloak_id'),
    sa.UniqueConstraint('legajo_evaluador'),
    sa.UniqueConstraint('username')
    )
    op.create_table('solicitudes_equivalencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_solicitud', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('nombre_solicitante', sa.String(length=64), nullable=False),
    sa.Column('apellido_solicitante', sa.String(length=64), nullable=False),
    sa.Column('dni_solicitante', sa.String(length=20), nullable=False),
    sa.Column('legajo_crub', sa.String(length=20), nullable=False),
    sa.Column('correo_solicitante', sa.String(length=120), nullable=False),
    sa.Column('institucion_origen', sa.String(length=200), nullable=False),
    sa.Column('carrera_origen', sa.String(length=200), nullable=False),
    sa.Column('carrera_crub_destino', sa.String(length=200), nullable=False),
    sa.Column('observaciones_solicitante', sa.Text(), nullable=True),
    sa.Column('evaluador_id', sa.Integer(), nullable=True),
    sa.Column('id_archivo_solicitud', sa.String(length=100), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=True),
    sa.Column('google_drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('google_drive_folder_id', sa.String(length=100), nullable=True),
    sa.Column('google_drive_folder_name', sa.String(length=255), nullable=True),
    sa.Column('google_drive_folder_url', sa.String(length=500), nullable=True),
    sa.Column('dictamen_final_file_id', sa.String(length=100), nullable=True),
    sa.Column('dictamen_final_url', sa.String(length=500), nullable=True),
    sa.Column('firma_evaluador', sa.String(length=255), nullable=True),
    sa.Column('doc_complementaria_file_id', sa.String(length=100), nullable=True),
    sa.Column('doc_complementaria_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_solicitud')
    )
    op.create_table('dictamenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asignatura_origen', sa.String(length=200), nullable=False),
    sa.Column('asignatura_destino', sa.String(length=200), nullable=True),
    sa.Column('tipo_equivalencia', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_dictamen', sa.DateTime(), nullable=True),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('evaluador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_equivalencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dictamenes')
    op.drop_table('solicitudes_equivalencia')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
