"""Add dictamen final fields to SolicitudEquivalencia

Revision ID: add_dictamen_final_fields
Revises: 3bd59c8c6557
Create Date: 2025-05-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_dictamen_final_fields'
down_revision = '3bd59c8c6557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_equivalencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dictamen_final_file_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dictamen_final_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_equivalencia', schema=None) as batch_op:
        batch_op.drop_column('dictamen_final_url')
        batch_op.drop_column('dictamen_final_file_id')

    # ### end Alembic commands ###
